#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

start_service() {
    procd_open_instance "uwebfilterd"
    procd_set_param command "/usr/bin/uwebfilterd /etc/uwebfilterd/config"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
